version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: PostgresContainer
    restart: always
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/
    networks:
      - my_network

  broker:
    image: apache/activemq-artemis:latest
    container_name: apache-artemis
    restart: always
    environment:
      - APACHE_USER=artemis
      - APACHE_PASSWORD=artemis

    ports:
      - '8161:8161'
      - '61616:61616'


  app:
    build: .
    container_name: training-plan-app
    restart: always

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
    ports:
      - '8080:8080'
    networks:
      - my_network
volumes:
  postgres_db:
    driver: local

networks:
  my_network: